[package]
name = "trading_module"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.28"
serde_json = "1.0"
mockito = "1.0.2"
tokio = {version = "1", features = ["full"]}
trading_bot_lib = { path = "../trading_bot_lib" }

[dependencies.redis]
version = "0.23"
features = ["aio", "tokio-comp"]

[dependencies.reqwest]
version = "0.11"
features = ["json"]